name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x
      
      # Instalar todas as dependências NPM/Yarn
      - name: Install dependencies
        run: yarn
        
      # Executar a build
      - name: Run build
        run: yarn build

      - name: copy dist to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist"
          target: "test"

# Copiar pasta dist pra dentro da Digital Ocean

# Subistituir o código existente na pasta "dist" pelo novo código
# Executar "yarn" na Digital Ocean
# Executar as migrations do TypeORM
#Restart no servidor Node.js
